name: publish docker images iota
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Node
        uses: docker/build-push-action@v4
        with:
          context: ./fogledger/images/iota
          file: ./fogledger/images/iota/iota.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/fogbed-iota-node:${{  github.ref_name }}
      
      - name: Build and push IotaApi
        uses: docker/build-push-action@v4
        with:
          context: ./fogledger/images/iota
          file: ./fogledger/images/iota/iota-explorer-api.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/fogbed-iota-api:${{  github.ref_name }}
      
      - name: Build and push IotaWebApp
        uses: docker/build-push-action@v4
        with:
          context: ./fogledger/images/iota
          file: ./fogledger/images/iota/iota-explorer-web-app.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/fogbed-iota-web-app:${{  github.ref_name }}